#!/bin/sh

#Autogenerated filename#
log_filename=log_system_`expr $RANDOM \* $RANDOM - $RANDOM`.log
log_dir=/tmp
first_running=1

logsystem_do_log(){
	log_path=$log_dir/$log_filename
	if [ -n "$2" ]; then
		header=$2
	fi
	echo "<<<<------BEGIN log line----------------------------" >> $log_path
    printf "[[[ `date` ]]]-($header)\n -- $1 \n" >> $log_path
	echo "----------END log line-------------------------->>>>" >> $log_path
}	


logsystem_is_log_path_seted(){
	if [ -z "$log_filename" ]; then
		logsystem_do_log "[ERROR]:The log_filename is not seted..."		
		exit 1
	fi
}


logsystem_set_log_filename(){
	if [ -n "$1" ]; then
		log_filename="$1"
	fi
}
