#!/bin/bash
#Las siguientes 2 líneas no funcionan...
#####export PGPASSFILE="/home/facundo/Programas/Postgres/pgpass.conf"
#####mysql --defaults-extra-file=/home/facundo/Programas/MySQL/mysql-opts

#script-version
VERSION=0.3.0

###Eclipse Luna
#ECLIPSE_HOME=/home/facundo/Documentos/Trabajos/SeDiCi/Entornos/eclipse
###Eclipse Neon
ECLIPSE_DIR_VERSION="4.6.3"
ECLIPSE_HOME=/home/facundo/Programas/eclipse_neon/$ECLIPSE_DIR_VERSION
CURRENT_DIR=`pwd`

#Para resolver problema de visualización en entorno KDE
export SWT_GTK3=0


mensaje(){
 echo "================================================================"
 echo "================$1================"
 echo "================================================================"
}

get_eclipse_version(){
  if [ -f "$ECLIPSE_HOME/.eclipseproduct" ];then
     more "$ECLIPSE_HOME/.eclipseproduct" | grep version | sed 's/version=//g'
  else
     printf "unknown"
  fi
}

is_eclipse_open(){

    ps au | awk "{ print \$11 }" | grep "$ECLIPSE_HOME/eclipse" > /dev/null
    if [ $? -eq 0 ]; then
        echo "Eclipse is already open..."
        exit 0
    fi
}

test_finalization(){
  if [ "$?" -ne 0 ];then
    mensaje "Se ha generado un error..."
    exit 1
  fi
}

ECLIPSE_VERSION=`get_eclipse_version`

#####  INIT  #####
while getopts ':psvh' OPTION; do
	case $OPTION in
		p) cd ~
		   su -c "pg_ctl start" postgres
		   test_finalization
		   cd $CURRENT_DIR
		   ;;

		s) systemctl start mysqld.service
		   test_finalization
		   ;;
		v) #Imprimiento versión de eclipse y del script
		   printf "* * * *\n* * *\n* *\n*ECLIPSE VERSION -->  $ECLIPSE_VERSION\n*OPEN-ECLIPSE VERSION --> $VERSION\n* *\n* * *\n* * * *\n"
		   exit 3
		   ;;
        h)
            echo "[HELP] This program starts eclipse located in '$ECLIPSE_HOME', besides it accepts parameters."
            echo "-p: start postrgesql."
            echo "-s: start mysql."
            echo "-v: show the current eclipse version"
            echo "-h: show this help text."
            exit 0
            ;;
		?)
		   echo "Parámetro inválido."
		   exit 2
		   ;;
	esac
done

is_eclipse_open
bash -c "$ECLIPSE_HOME/eclipse& 2> /dev/null"

